### PR TITLE
Fixed some rules

### PR DESCRIPTION
**Pull request by The-Commissioner**
Fixed sites: askvg.com and ghacks.net
Some of the rules that were there were not applied to the inside pages of the site.
Some of the cosmetic rules were overlapping in these two sites.
Now fixed. Pls check and report how these sites behave now.

### CODE REVIEW

**Comment by CHEF-KOCH** [comment]
Good job! @The-Commissioner

Can you also take a look at the GitHub profile loading issue in uBlock? I haven't figured out what is causing it, might be DOM or filter list issue. Whenever I try to load/visit someones GitHub profile, I see a white page. For example, [your profile page](https://github.com/The-Commissioner).

Maybe if you have time :laughing: ...

**Comment by The-Commissioner** [comment]
Thanx @CHEF-KOCH 
Regarding github, I looked at your rules, I'm still figuring what rule blocks what(maybe they are even outdated as well.)But I gave priority to the issue you mentioned above. It seems another bad filter in your static filter list is causing the no viewing of github profiles.
https://github.com/The-Commissioner/NoScript-Whitelist/blob/1a57bcbd1d2205cd271fb7743bd3804e7217c270/uBlock%E2%82%80/my-ublock-static-filters_2017-09-01_02.35.50.txt#L330

`github.com##.mt-4`

So if you comment out the rule or remove that rule, it should be fine.
Please try it and give feedback whether it solves the problem or not. :-)

**Comment by CHEF-KOCH** [comment]
invision-board-france-464-78c08

**Comment by The-Commissioner** [comment]
@CHEF-KOCH for github, can you tell me what all you want to hide, so I can see your rules and optimize them if necessary.
I would need screenshot of elements you want to hide and possible link to github page where that element is.
Same for Mdl,I think your rules are old bcuz they have .info domain which is old. So if you can point like github, it would be much easier.

**Comment by CHEF-KOCH** [comment]
Well, don't make the mistake to say 'my list' it's a community driven list. Sure, thanks for the effort but currently I'm happy with GitHub how it looks, there are only the little ProTip! 'ads' at the bottom of the main-page + issue tickets but I not see this critical. The question is also what really makes sense to hide, I doubt that hiding these elements have any effect on loading speed together with the fact that some beginners might want to see them. 

So (personally) I would like to let it go, instead I think I will take a look at obsolete entries at the weekend. I'll chill over the next few days.

giphy

**Comment by CHEF-KOCH** [comment]
@The-Commissioner 

I gave you commit permissions. So you can push changes without pull request first.

**Comment by The-Commissioner** [comment]
@CHEF-KOCH Thank you but I don't know what more I can contribute now. Those are sites I don't visit, so I don't know what rule is blocking what.
I haven't accepted that invitation just yet because it may give me privilege.
So if you make it clear what my role or what you expect from my side and tell me that there is a contribution I can make, then me acceoting that invite will be useful. Plz clarify.

**Comment by CHEF-KOCH** [comment]
You don't need a specific role here. I know you're in to the entire uBlock/AdGuard topic so it's more a '4eyes' principle, if you find something I'm sure you're able to correct it without me. That's why I trust you on this and gave you the permission, well of course it's up to you.

I would be thankfully if I get more committer on my projects because it's very time consuming to maintain it.

**Comment by The-Commissioner** [comment]
Ok understood. Thanx for the opportunity.

**Pull request merged**
